environment:
  matrix:
    - nodejs_version: "6"
install:
  - ps: Install-Product node $env:nodejs_version
  - IF %nodejs_version% EQU 0.8 npm -g install npm@2
  - IF %nodejs_version% EQU 0.8 set PATH=%APPDATA%\npm;%PATH%
  - npm -g install npm
  - IF %nodejs_version% NEQ 0.8 set PATH=%APPDATA%\npm;%PATH%
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: off